
// ALERT MODALS
export const DISPLAY_ALERT = "DISPLAY_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"

// REGISTRATION ACTIONS
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_FAILURE"

// LOGIN ACTIONS